MERGE INTO RATING KEY (ID, RATING) VALUES (1, 'G');
MERGE INTO RATING KEY (ID, RATING) VALUES (2, 'PG');
MERGE INTO RATING KEY (ID, RATING) VALUES (3, 'PG-13');
MERGE INTO RATING KEY (ID, RATING) VALUES (4, 'R');
MERGE INTO RATING KEY (ID, RATING) VALUES (5, 'NC-17');

MERGE INTO GENRE KEY (ID, GENRE) VALUES (1, 'Комедия');
MERGE INTO GENRE KEY (ID, GENRE) VALUES (2, 'Драма');
MERGE INTO GENRE KEY (ID, GENRE) VALUES (3, 'Мультфильм');
MERGE INTO GENRE KEY (ID, GENRE) VALUES (4, 'Фантастика');
MERGE INTO GENRE KEY (ID, GENRE) VALUES (5, 'Ужасы');
MERGE INTO GENRE KEY (ID, GENRE) VALUES (6, 'Мелодрама');